# ==== General Settings ====
seed: 333
output_dir: reports
excel_path: data/Quotazioni_Fantacalcio_Stagione_2025_26.xlsx   # Path to your updated weekly Excel
data_path: data/Quotazioni_Fantacalcio_Stagione_2025_26.xlsx
tier_column: "Quotazione"

# Tier quantiles for player classification
tier_quantiles:
  elite: 0.90
  high: 0.65
  medium: 0.25
  low: 0.20

# ==== Modules ====
primary_module: "4-2-3-1"
backup_modules:
  - "4-3-3"
  - "4-4-2"

# Role mapping for each module (Mantra roles)
modules:
  "4-2-3-1":
    Por: 1
    Dc: 2
    Dd: 1
    Ds: 1
    M: 1
    C: 1
    W: 2
    T: 1
    Pc: 1
  "4-3-3":
    Por: 1
    Dc: 2
    Dd: 1
    Ds: 1
    M: 1
    C: 2
    W: 2
    Pc: 1
  "4-4-2":
    Por: 1
    Dc: 2
    Dd: 1
    Ds: 1
    M: 1
    C: 1
    W: 2
    A: 1
    Pc: 1

# ==== Supply (league-wide player counts per role) ====
supply:
  Por: 12
  Dc: 26
  Dd: 14
  Ds: 14
  E: 12
  M: 24
  C: 24
  W: 18
  T: 18
  A: 18
  Pc: 18

# ==== Simulation Settings ====
num_teams: 8
total_budget: 400
budget_cap: 400
num_simulations: 1000

# ==== Opponent Modeling ====
plus_one_rule: true
opp_shading_mu: 0.75
opp_shading_sd: 0.07
opp_plus_one_prob: 0.6

# ==== Analysis Settings ====
scarcity_analysis:
  enabled: true
  risk_factor_weight: 0.3
  consistency_weight: 0.4
  upside_weight: 0.3

shading_analysis:
  enabled: true
  monte_carlo_runs: 10000
  confidence_level: 0.95
  ownership_variance: 0.15

auction_flow_analysis:
  enabled: true
  nomination_rounds: 25
  strategy_types:
    - aggressive
    - patient
    - value

# ==== Bids Round 1 Settings ====
bids_round1:
  enabled: true
  reserve_credits: 80
  filter_to_targets: true  # Only generate recommendations for formation-required players
  target_multiplier: 2.5  # How many players per position to target (e.g., 2.5x formation requirements)
  max_total_budget: 2000  # Maximum total recommended budget

# ==== Audit Settings ====
audit:
  strict: true
  include_excel_hash: true
  include_git_commit: true

# ==== Report Settings ====
report_title: "Fantacalcio Simulation Suite Report"
author: "Fantacalcio Analysis System"
generate_pdf: true
include_visualizations: true
